# -*- coding: utf-8 -*-

# $Id$


# for the sake of autogenerated documentation
def make_unique_named_symbol(name):
    class Tmp(object):
        def __repr__(self):
            return name
    return Tmp()


NoDefault = make_unique_named_symbol("NoDefault")


class TypedObject(object):

    def __init__(self, schema):
        self.__dict__["_values"] = {k: v[0] for k, v in schema.items()}
        self.__dict__["_validators"] = {k: v[1] for k, v in schema.items()}

    def __getattr__(self, name):
        if name not in self._validators:
            raise AttributeError(name)
        value = self._values.get(name)
        if value is NoDefault:
            raise AttributeError(name)
        return value

    def __setattr__(self, name, value):
        if name not in self._validators:
            raise AttributeError(name)
        validator = self._validators[name]
        if callable(validator):
            try:
                value = validator(value)
            except ValueError:
                raise ValueError("Wrong value '%s' for option '%s'" % (value, name))
        self._values[name] = value
